#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnBanXe.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyXe")]
	public partial class dbXeMerDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertADMIN(ADMIN instance);
    partial void UpdateADMIN(ADMIN instance);
    partial void DeleteADMIN(ADMIN instance);
    partial void InsertXe(Xe instance);
    partial void UpdateXe(Xe instance);
    partial void DeleteXe(Xe instance);
    partial void InsertChiTietDonDatHangDC(ChiTietDonDatHangDC instance);
    partial void UpdateChiTietDonDatHangDC(ChiTietDonDatHangDC instance);
    partial void DeleteChiTietDonDatHangDC(ChiTietDonDatHangDC instance);
    partial void InsertChiTietPhuKien(ChiTietPhuKien instance);
    partial void UpdateChiTietPhuKien(ChiTietPhuKien instance);
    partial void DeleteChiTietPhuKien(ChiTietPhuKien instance);
    partial void InsertClass(Class instance);
    partial void UpdateClass(Class instance);
    partial void DeleteClass(Class instance);
    partial void InsertDoChoiXe(DoChoiXe instance);
    partial void UpdateDoChoiXe(DoChoiXe instance);
    partial void DeleteDoChoiXe(DoChoiXe instance);
    partial void InsertDonDatHang(DonDatHang instance);
    partial void UpdateDonDatHang(DonDatHang instance);
    partial void DeleteDonDatHang(DonDatHang instance);
    partial void InsertDonDatHangDoChoi(DonDatHangDoChoi instance);
    partial void UpdateDonDatHangDoChoi(DonDatHangDoChoi instance);
    partial void DeleteDonDatHangDoChoi(DonDatHangDoChoi instance);
    partial void InsertKhachHang(KhachHang instance);
    partial void UpdateKhachHang(KhachHang instance);
    partial void DeleteKhachHang(KhachHang instance);
    partial void InsertLoaiDoChoiXe(LoaiDoChoiXe instance);
    partial void UpdateLoaiDoChoiXe(LoaiDoChoiXe instance);
    partial void DeleteLoaiDoChoiXe(LoaiDoChoiXe instance);
    partial void InsertPhuKien(PhuKien instance);
    partial void UpdatePhuKien(PhuKien instance);
    partial void DeletePhuKien(PhuKien instance);
    #endregion
		
		public dbXeMerDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QuanLyXeConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbXeMerDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbXeMerDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbXeMerDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbXeMerDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ADMIN> ADMINs
		{
			get
			{
				return this.GetTable<ADMIN>();
			}
		}
		
		public System.Data.Linq.Table<Xe> Xes
		{
			get
			{
				return this.GetTable<Xe>();
			}
		}
		
		public System.Data.Linq.Table<ChiTietDonDatHangDC> ChiTietDonDatHangDCs
		{
			get
			{
				return this.GetTable<ChiTietDonDatHangDC>();
			}
		}
		
		public System.Data.Linq.Table<ChiTietPhuKien> ChiTietPhuKiens
		{
			get
			{
				return this.GetTable<ChiTietPhuKien>();
			}
		}
		
		public System.Data.Linq.Table<Class> Classes
		{
			get
			{
				return this.GetTable<Class>();
			}
		}
		
		public System.Data.Linq.Table<DoChoiXe> DoChoiXes
		{
			get
			{
				return this.GetTable<DoChoiXe>();
			}
		}
		
		public System.Data.Linq.Table<DonDatHang> DonDatHangs
		{
			get
			{
				return this.GetTable<DonDatHang>();
			}
		}
		
		public System.Data.Linq.Table<DonDatHangDoChoi> DonDatHangDoChois
		{
			get
			{
				return this.GetTable<DonDatHangDoChoi>();
			}
		}
		
		public System.Data.Linq.Table<KhachHang> KhachHangs
		{
			get
			{
				return this.GetTable<KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<LoaiDoChoiXe> LoaiDoChoiXes
		{
			get
			{
				return this.GetTable<LoaiDoChoiXe>();
			}
		}
		
		public System.Data.Linq.Table<PhuKien> PhuKiens
		{
			get
			{
				return this.GetTable<PhuKien>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ADMIN")]
	public partial class ADMIN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaAdmin;
		
		private string _HoTen;
		
		private string _DiaChi;
		
		private string _DienThoai;
		
		private string _TenDN;
		
		private string _MatKhau;
		
		private string _Email;
		
		private System.Nullable<int> _Quyen;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaAdminChanging(int value);
    partial void OnMaAdminChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnDienThoaiChanging(string value);
    partial void OnDienThoaiChanged();
    partial void OnTenDNChanging(string value);
    partial void OnTenDNChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnQuyenChanging(System.Nullable<int> value);
    partial void OnQuyenChanged();
    #endregion
		
		public ADMIN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaAdmin", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaAdmin
		{
			get
			{
				return this._MaAdmin;
			}
			set
			{
				if ((this._MaAdmin != value))
				{
					this.OnMaAdminChanging(value);
					this.SendPropertyChanging();
					this._MaAdmin = value;
					this.SendPropertyChanged("MaAdmin");
					this.OnMaAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoai", DbType="VarChar(10)")]
		public string DienThoai
		{
			get
			{
				return this._DienThoai;
			}
			set
			{
				if ((this._DienThoai != value))
				{
					this.OnDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._DienThoai = value;
					this.SendPropertyChanged("DienThoai");
					this.OnDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDN", DbType="VarChar(15)")]
		public string TenDN
		{
			get
			{
				return this._TenDN;
			}
			set
			{
				if ((this._TenDN != value))
				{
					this.OnTenDNChanging(value);
					this.SendPropertyChanging();
					this._TenDN = value;
					this.SendPropertyChanged("TenDN");
					this.OnTenDNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(15)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quyen", DbType="Int")]
		public System.Nullable<int> Quyen
		{
			get
			{
				return this._Quyen;
			}
			set
			{
				if ((this._Quyen != value))
				{
					this.OnQuyenChanging(value);
					this.SendPropertyChanging();
					this._Quyen = value;
					this.SendPropertyChanged("Quyen");
					this.OnQuyenChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Xe")]
	public partial class Xe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaXe;
		
		private string _LoaiXe;
		
		private string _TenXe;
		
		private System.Nullable<decimal> _GiaXe;
		
		private string _AnhBia;
		
		private string _MoTa;
		
		private System.Nullable<System.DateTime> _NgayCapNhat;
		
		private System.Nullable<int> _MaClass;
		
		private EntityRef<Class> _Class;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaXeChanging(int value);
    partial void OnMaXeChanged();
    partial void OnLoaiXeChanging(string value);
    partial void OnLoaiXeChanged();
    partial void OnTenXeChanging(string value);
    partial void OnTenXeChanged();
    partial void OnGiaXeChanging(System.Nullable<decimal> value);
    partial void OnGiaXeChanged();
    partial void OnAnhBiaChanging(string value);
    partial void OnAnhBiaChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    partial void OnNgayCapNhatChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayCapNhatChanged();
    partial void OnMaClassChanging(System.Nullable<int> value);
    partial void OnMaClassChanged();
    #endregion
		
		public Xe()
		{
			this._Class = default(EntityRef<Class>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaXe", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaXe
		{
			get
			{
				return this._MaXe;
			}
			set
			{
				if ((this._MaXe != value))
				{
					this.OnMaXeChanging(value);
					this.SendPropertyChanging();
					this._MaXe = value;
					this.SendPropertyChanged("MaXe");
					this.OnMaXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiXe", DbType="VarChar(30)")]
		public string LoaiXe
		{
			get
			{
				return this._LoaiXe;
			}
			set
			{
				if ((this._LoaiXe != value))
				{
					this.OnLoaiXeChanging(value);
					this.SendPropertyChanging();
					this._LoaiXe = value;
					this.SendPropertyChanged("LoaiXe");
					this.OnLoaiXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenXe", DbType="VarChar(100)")]
		public string TenXe
		{
			get
			{
				return this._TenXe;
			}
			set
			{
				if ((this._TenXe != value))
				{
					this.OnTenXeChanging(value);
					this.SendPropertyChanging();
					this._TenXe = value;
					this.SendPropertyChanged("TenXe");
					this.OnTenXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaXe", DbType="Money")]
		public System.Nullable<decimal> GiaXe
		{
			get
			{
				return this._GiaXe;
			}
			set
			{
				if ((this._GiaXe != value))
				{
					this.OnGiaXeChanging(value);
					this.SendPropertyChanging();
					this._GiaXe = value;
					this.SendPropertyChanged("GiaXe");
					this.OnGiaXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnhBia", DbType="VarChar(50)")]
		public string AnhBia
		{
			get
			{
				return this._AnhBia;
			}
			set
			{
				if ((this._AnhBia != value))
				{
					this.OnAnhBiaChanging(value);
					this.SendPropertyChanging();
					this._AnhBia = value;
					this.SendPropertyChanged("AnhBia");
					this.OnAnhBiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCapNhat", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> NgayCapNhat
		{
			get
			{
				return this._NgayCapNhat;
			}
			set
			{
				if ((this._NgayCapNhat != value))
				{
					this.OnNgayCapNhatChanging(value);
					this.SendPropertyChanging();
					this._NgayCapNhat = value;
					this.SendPropertyChanged("NgayCapNhat");
					this.OnNgayCapNhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaClass", DbType="Int")]
		public System.Nullable<int> MaClass
		{
			get
			{
				return this._MaClass;
			}
			set
			{
				if ((this._MaClass != value))
				{
					if (this._Class.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaClassChanging(value);
					this.SendPropertyChanging();
					this._MaClass = value;
					this.SendPropertyChanged("MaClass");
					this.OnMaClassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Class_Xe", Storage="_Class", ThisKey="MaClass", OtherKey="MaClass", IsForeignKey=true)]
		public Class Class
		{
			get
			{
				return this._Class.Entity;
			}
			set
			{
				Class previousValue = this._Class.Entity;
				if (((previousValue != value) 
							|| (this._Class.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Class.Entity = null;
						previousValue.Xes.Remove(this);
					}
					this._Class.Entity = value;
					if ((value != null))
					{
						value.Xes.Add(this);
						this._MaClass = value.MaClass;
					}
					else
					{
						this._MaClass = default(Nullable<int>);
					}
					this.SendPropertyChanged("Class");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietDonDatHangDC")]
	public partial class ChiTietDonDatHangDC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _STT;
		
		private int _MaDonHangDC;
		
		private System.Nullable<int> _MaKH;
		
		private string _TenDC;
		
		private System.Nullable<decimal> _GiaDC;
		
		private System.Nullable<System.DateTime> _NgayDat;
		
		private System.Nullable<int> _SoLuong;
		
		private EntityRef<DonDatHangDoChoi> _DonDatHangDoChoi;
		
		private EntityRef<KhachHang> _KhachHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSTTChanging(int value);
    partial void OnSTTChanged();
    partial void OnMaDonHangDCChanging(int value);
    partial void OnMaDonHangDCChanged();
    partial void OnMaKHChanging(System.Nullable<int> value);
    partial void OnMaKHChanged();
    partial void OnTenDCChanging(string value);
    partial void OnTenDCChanged();
    partial void OnGiaDCChanging(System.Nullable<decimal> value);
    partial void OnGiaDCChanged();
    partial void OnNgayDatChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDatChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    #endregion
		
		public ChiTietDonDatHangDC()
		{
			this._DonDatHangDoChoi = default(EntityRef<DonDatHangDoChoi>);
			this._KhachHang = default(EntityRef<KhachHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int STT
		{
			get
			{
				return this._STT;
			}
			set
			{
				if ((this._STT != value))
				{
					this.OnSTTChanging(value);
					this.SendPropertyChanging();
					this._STT = value;
					this.SendPropertyChanged("STT");
					this.OnSTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDonHangDC", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaDonHangDC
		{
			get
			{
				return this._MaDonHangDC;
			}
			set
			{
				if ((this._MaDonHangDC != value))
				{
					if (this._DonDatHangDoChoi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDonHangDCChanging(value);
					this.SendPropertyChanging();
					this._MaDonHangDC = value;
					this.SendPropertyChanged("MaDonHangDC");
					this.OnMaDonHangDCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Int")]
		public System.Nullable<int> MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDC", DbType="NVarChar(100)")]
		public string TenDC
		{
			get
			{
				return this._TenDC;
			}
			set
			{
				if ((this._TenDC != value))
				{
					this.OnTenDCChanging(value);
					this.SendPropertyChanging();
					this._TenDC = value;
					this.SendPropertyChanged("TenDC");
					this.OnTenDCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaDC", DbType="Decimal(9,2)")]
		public System.Nullable<decimal> GiaDC
		{
			get
			{
				return this._GiaDC;
			}
			set
			{
				if ((this._GiaDC != value))
				{
					this.OnGiaDCChanging(value);
					this.SendPropertyChanging();
					this._GiaDC = value;
					this.SendPropertyChanged("GiaDC");
					this.OnGiaDCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDat", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> NgayDat
		{
			get
			{
				return this._NgayDat;
			}
			set
			{
				if ((this._NgayDat != value))
				{
					this.OnNgayDatChanging(value);
					this.SendPropertyChanging();
					this._NgayDat = value;
					this.SendPropertyChanged("NgayDat");
					this.OnNgayDatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DonDatHangDoChoi_ChiTietDonDatHangDC", Storage="_DonDatHangDoChoi", ThisKey="MaDonHangDC", OtherKey="MaDonHangDC", IsForeignKey=true)]
		public DonDatHangDoChoi DonDatHangDoChoi
		{
			get
			{
				return this._DonDatHangDoChoi.Entity;
			}
			set
			{
				DonDatHangDoChoi previousValue = this._DonDatHangDoChoi.Entity;
				if (((previousValue != value) 
							|| (this._DonDatHangDoChoi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DonDatHangDoChoi.Entity = null;
						previousValue.ChiTietDonDatHangDCs.Remove(this);
					}
					this._DonDatHangDoChoi.Entity = value;
					if ((value != null))
					{
						value.ChiTietDonDatHangDCs.Add(this);
						this._MaDonHangDC = value.MaDonHangDC;
					}
					else
					{
						this._MaDonHangDC = default(int);
					}
					this.SendPropertyChanged("DonDatHangDoChoi");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_ChiTietDonDatHangDC", Storage="_KhachHang", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.ChiTietDonDatHangDCs.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.ChiTietDonDatHangDCs.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(Nullable<int>);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietPhuKien")]
	public partial class ChiTietPhuKien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Ma;
		
		private string _TenPhukien;
		
		private string _AnhPhuKien;
		
		private string _MoTa1;
		
		private string _Mota2;
		
		private System.Nullable<int> _MaPhuKien;
		
		private EntityRef<PhuKien> _PhuKien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaChanging(int value);
    partial void OnMaChanged();
    partial void OnTenPhukienChanging(string value);
    partial void OnTenPhukienChanged();
    partial void OnAnhPhuKienChanging(string value);
    partial void OnAnhPhuKienChanged();
    partial void OnMoTa1Changing(string value);
    partial void OnMoTa1Changed();
    partial void OnMota2Changing(string value);
    partial void OnMota2Changed();
    partial void OnMaPhuKienChanging(System.Nullable<int> value);
    partial void OnMaPhuKienChanged();
    #endregion
		
		public ChiTietPhuKien()
		{
			this._PhuKien = default(EntityRef<PhuKien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Ma
		{
			get
			{
				return this._Ma;
			}
			set
			{
				if ((this._Ma != value))
				{
					this.OnMaChanging(value);
					this.SendPropertyChanging();
					this._Ma = value;
					this.SendPropertyChanged("Ma");
					this.OnMaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenPhukien", DbType="NVarChar(50)")]
		public string TenPhukien
		{
			get
			{
				return this._TenPhukien;
			}
			set
			{
				if ((this._TenPhukien != value))
				{
					this.OnTenPhukienChanging(value);
					this.SendPropertyChanging();
					this._TenPhukien = value;
					this.SendPropertyChanged("TenPhukien");
					this.OnTenPhukienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnhPhuKien", DbType="VarChar(50)")]
		public string AnhPhuKien
		{
			get
			{
				return this._AnhPhuKien;
			}
			set
			{
				if ((this._AnhPhuKien != value))
				{
					this.OnAnhPhuKienChanging(value);
					this.SendPropertyChanging();
					this._AnhPhuKien = value;
					this.SendPropertyChanged("AnhPhuKien");
					this.OnAnhPhuKienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa1", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string MoTa1
		{
			get
			{
				return this._MoTa1;
			}
			set
			{
				if ((this._MoTa1 != value))
				{
					this.OnMoTa1Changing(value);
					this.SendPropertyChanging();
					this._MoTa1 = value;
					this.SendPropertyChanged("MoTa1");
					this.OnMoTa1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mota2", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Mota2
		{
			get
			{
				return this._Mota2;
			}
			set
			{
				if ((this._Mota2 != value))
				{
					this.OnMota2Changing(value);
					this.SendPropertyChanging();
					this._Mota2 = value;
					this.SendPropertyChanged("Mota2");
					this.OnMota2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhuKien", DbType="Int")]
		public System.Nullable<int> MaPhuKien
		{
			get
			{
				return this._MaPhuKien;
			}
			set
			{
				if ((this._MaPhuKien != value))
				{
					if (this._PhuKien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPhuKienChanging(value);
					this.SendPropertyChanging();
					this._MaPhuKien = value;
					this.SendPropertyChanged("MaPhuKien");
					this.OnMaPhuKienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhuKien_ChiTietPhuKien", Storage="_PhuKien", ThisKey="MaPhuKien", OtherKey="MaPhuKien", IsForeignKey=true)]
		public PhuKien PhuKien
		{
			get
			{
				return this._PhuKien.Entity;
			}
			set
			{
				PhuKien previousValue = this._PhuKien.Entity;
				if (((previousValue != value) 
							|| (this._PhuKien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhuKien.Entity = null;
						previousValue.ChiTietPhuKiens.Remove(this);
					}
					this._PhuKien.Entity = value;
					if ((value != null))
					{
						value.ChiTietPhuKiens.Add(this);
						this._MaPhuKien = value.MaPhuKien;
					}
					else
					{
						this._MaPhuKien = default(Nullable<int>);
					}
					this.SendPropertyChanged("PhuKien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Class")]
	public partial class Class : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaClass;
		
		private string _TenClass;
		
		private EntitySet<Xe> _Xes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaClassChanging(int value);
    partial void OnMaClassChanged();
    partial void OnTenClassChanging(string value);
    partial void OnTenClassChanged();
    #endregion
		
		public Class()
		{
			this._Xes = new EntitySet<Xe>(new Action<Xe>(this.attach_Xes), new Action<Xe>(this.detach_Xes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaClass", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaClass
		{
			get
			{
				return this._MaClass;
			}
			set
			{
				if ((this._MaClass != value))
				{
					this.OnMaClassChanging(value);
					this.SendPropertyChanging();
					this._MaClass = value;
					this.SendPropertyChanged("MaClass");
					this.OnMaClassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenClass", DbType="NVarChar(50)")]
		public string TenClass
		{
			get
			{
				return this._TenClass;
			}
			set
			{
				if ((this._TenClass != value))
				{
					this.OnTenClassChanging(value);
					this.SendPropertyChanging();
					this._TenClass = value;
					this.SendPropertyChanged("TenClass");
					this.OnTenClassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Class_Xe", Storage="_Xes", ThisKey="MaClass", OtherKey="MaClass")]
		public EntitySet<Xe> Xes
		{
			get
			{
				return this._Xes;
			}
			set
			{
				this._Xes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Xes(Xe entity)
		{
			this.SendPropertyChanging();
			entity.Class = this;
		}
		
		private void detach_Xes(Xe entity)
		{
			this.SendPropertyChanging();
			entity.Class = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DoChoiXe")]
	public partial class DoChoiXe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDC;
		
		private string _LoaiDC;
		
		private string _TenDC;
		
		private System.Nullable<decimal> _GiaDC;
		
		private string _AnhDC;
		
		private string _MoTa;
		
		private System.Nullable<System.DateTime> _NgayCapNhat;
		
		private System.Nullable<int> _MaLoaiDC;
		
		private EntityRef<LoaiDoChoiXe> _LoaiDoChoiXe;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDCChanging(int value);
    partial void OnMaDCChanged();
    partial void OnLoaiDCChanging(string value);
    partial void OnLoaiDCChanged();
    partial void OnTenDCChanging(string value);
    partial void OnTenDCChanged();
    partial void OnGiaDCChanging(System.Nullable<decimal> value);
    partial void OnGiaDCChanged();
    partial void OnAnhDCChanging(string value);
    partial void OnAnhDCChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    partial void OnNgayCapNhatChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayCapNhatChanged();
    partial void OnMaLoaiDCChanging(System.Nullable<int> value);
    partial void OnMaLoaiDCChanged();
    #endregion
		
		public DoChoiXe()
		{
			this._LoaiDoChoiXe = default(EntityRef<LoaiDoChoiXe>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDC", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaDC
		{
			get
			{
				return this._MaDC;
			}
			set
			{
				if ((this._MaDC != value))
				{
					this.OnMaDCChanging(value);
					this.SendPropertyChanging();
					this._MaDC = value;
					this.SendPropertyChanged("MaDC");
					this.OnMaDCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiDC", DbType="NVarChar(50)")]
		public string LoaiDC
		{
			get
			{
				return this._LoaiDC;
			}
			set
			{
				if ((this._LoaiDC != value))
				{
					this.OnLoaiDCChanging(value);
					this.SendPropertyChanging();
					this._LoaiDC = value;
					this.SendPropertyChanged("LoaiDC");
					this.OnLoaiDCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDC", DbType="NVarChar(100)")]
		public string TenDC
		{
			get
			{
				return this._TenDC;
			}
			set
			{
				if ((this._TenDC != value))
				{
					this.OnTenDCChanging(value);
					this.SendPropertyChanging();
					this._TenDC = value;
					this.SendPropertyChanged("TenDC");
					this.OnTenDCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaDC", DbType="Money")]
		public System.Nullable<decimal> GiaDC
		{
			get
			{
				return this._GiaDC;
			}
			set
			{
				if ((this._GiaDC != value))
				{
					this.OnGiaDCChanging(value);
					this.SendPropertyChanging();
					this._GiaDC = value;
					this.SendPropertyChanged("GiaDC");
					this.OnGiaDCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnhDC", DbType="NVarChar(100)")]
		public string AnhDC
		{
			get
			{
				return this._AnhDC;
			}
			set
			{
				if ((this._AnhDC != value))
				{
					this.OnAnhDCChanging(value);
					this.SendPropertyChanging();
					this._AnhDC = value;
					this.SendPropertyChanged("AnhDC");
					this.OnAnhDCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCapNhat", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> NgayCapNhat
		{
			get
			{
				return this._NgayCapNhat;
			}
			set
			{
				if ((this._NgayCapNhat != value))
				{
					this.OnNgayCapNhatChanging(value);
					this.SendPropertyChanging();
					this._NgayCapNhat = value;
					this.SendPropertyChanged("NgayCapNhat");
					this.OnNgayCapNhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiDC", DbType="Int")]
		public System.Nullable<int> MaLoaiDC
		{
			get
			{
				return this._MaLoaiDC;
			}
			set
			{
				if ((this._MaLoaiDC != value))
				{
					if (this._LoaiDoChoiXe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLoaiDCChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiDC = value;
					this.SendPropertyChanged("MaLoaiDC");
					this.OnMaLoaiDCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiDoChoiXe_DoChoiXe", Storage="_LoaiDoChoiXe", ThisKey="MaLoaiDC", OtherKey="MaLoaiDC", IsForeignKey=true)]
		public LoaiDoChoiXe LoaiDoChoiXe
		{
			get
			{
				return this._LoaiDoChoiXe.Entity;
			}
			set
			{
				LoaiDoChoiXe previousValue = this._LoaiDoChoiXe.Entity;
				if (((previousValue != value) 
							|| (this._LoaiDoChoiXe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiDoChoiXe.Entity = null;
						previousValue.DoChoiXes.Remove(this);
					}
					this._LoaiDoChoiXe.Entity = value;
					if ((value != null))
					{
						value.DoChoiXes.Add(this);
						this._MaLoaiDC = value.MaLoaiDC;
					}
					else
					{
						this._MaLoaiDC = default(Nullable<int>);
					}
					this.SendPropertyChanged("LoaiDoChoiXe");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DonDatHang")]
	public partial class DonDatHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDonHang;
		
		private System.Nullable<int> _MaKH;
		
		private string _TenTK;
		
		private string _HoTen;
		
		private string _DienThoai;
		
		private string _DiaChi;
		
		private string _email;
		
		private System.Nullable<System.DateTime> _NgayDat;
		
		private string _LoaiXe;
		
		private string _TenXe;
		
		private EntityRef<KhachHang> _KhachHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDonHangChanging(int value);
    partial void OnMaDonHangChanged();
    partial void OnMaKHChanging(System.Nullable<int> value);
    partial void OnMaKHChanged();
    partial void OnTenTKChanging(string value);
    partial void OnTenTKChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnDienThoaiChanging(string value);
    partial void OnDienThoaiChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnNgayDatChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDatChanged();
    partial void OnLoaiXeChanging(string value);
    partial void OnLoaiXeChanged();
    partial void OnTenXeChanging(string value);
    partial void OnTenXeChanged();
    #endregion
		
		public DonDatHang()
		{
			this._KhachHang = default(EntityRef<KhachHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDonHang", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaDonHang
		{
			get
			{
				return this._MaDonHang;
			}
			set
			{
				if ((this._MaDonHang != value))
				{
					this.OnMaDonHangChanging(value);
					this.SendPropertyChanging();
					this._MaDonHang = value;
					this.SendPropertyChanged("MaDonHang");
					this.OnMaDonHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Int")]
		public System.Nullable<int> MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTK", DbType="NVarChar(50)")]
		public string TenTK
		{
			get
			{
				return this._TenTK;
			}
			set
			{
				if ((this._TenTK != value))
				{
					this.OnTenTKChanging(value);
					this.SendPropertyChanging();
					this._TenTK = value;
					this.SendPropertyChanged("TenTK");
					this.OnTenTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoai", DbType="VarChar(20)")]
		public string DienThoai
		{
			get
			{
				return this._DienThoai;
			}
			set
			{
				if ((this._DienThoai != value))
				{
					this.OnDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._DienThoai = value;
					this.SendPropertyChanged("DienThoai");
					this.OnDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDat", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> NgayDat
		{
			get
			{
				return this._NgayDat;
			}
			set
			{
				if ((this._NgayDat != value))
				{
					this.OnNgayDatChanging(value);
					this.SendPropertyChanging();
					this._NgayDat = value;
					this.SendPropertyChanged("NgayDat");
					this.OnNgayDatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiXe", DbType="VarChar(30)")]
		public string LoaiXe
		{
			get
			{
				return this._LoaiXe;
			}
			set
			{
				if ((this._LoaiXe != value))
				{
					this.OnLoaiXeChanging(value);
					this.SendPropertyChanging();
					this._LoaiXe = value;
					this.SendPropertyChanged("LoaiXe");
					this.OnLoaiXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenXe", DbType="VarChar(100)")]
		public string TenXe
		{
			get
			{
				return this._TenXe;
			}
			set
			{
				if ((this._TenXe != value))
				{
					this.OnTenXeChanging(value);
					this.SendPropertyChanging();
					this._TenXe = value;
					this.SendPropertyChanged("TenXe");
					this.OnTenXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_DonDatHang", Storage="_KhachHang", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.DonDatHangs.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.DonDatHangs.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(Nullable<int>);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DonDatHangDoChoi")]
	public partial class DonDatHangDoChoi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDonHangDC;
		
		private System.Nullable<int> _MaKH;
		
		private string _TenTK;
		
		private string _HoTen;
		
		private string _DiaChi;
		
		private string _DienThoai;
		
		private EntitySet<ChiTietDonDatHangDC> _ChiTietDonDatHangDCs;
		
		private EntityRef<KhachHang> _KhachHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDonHangDCChanging(int value);
    partial void OnMaDonHangDCChanged();
    partial void OnMaKHChanging(System.Nullable<int> value);
    partial void OnMaKHChanged();
    partial void OnTenTKChanging(string value);
    partial void OnTenTKChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnDienThoaiChanging(string value);
    partial void OnDienThoaiChanged();
    #endregion
		
		public DonDatHangDoChoi()
		{
			this._ChiTietDonDatHangDCs = new EntitySet<ChiTietDonDatHangDC>(new Action<ChiTietDonDatHangDC>(this.attach_ChiTietDonDatHangDCs), new Action<ChiTietDonDatHangDC>(this.detach_ChiTietDonDatHangDCs));
			this._KhachHang = default(EntityRef<KhachHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDonHangDC", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaDonHangDC
		{
			get
			{
				return this._MaDonHangDC;
			}
			set
			{
				if ((this._MaDonHangDC != value))
				{
					this.OnMaDonHangDCChanging(value);
					this.SendPropertyChanging();
					this._MaDonHangDC = value;
					this.SendPropertyChanged("MaDonHangDC");
					this.OnMaDonHangDCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Int")]
		public System.Nullable<int> MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTK", DbType="NVarChar(50)")]
		public string TenTK
		{
			get
			{
				return this._TenTK;
			}
			set
			{
				if ((this._TenTK != value))
				{
					this.OnTenTKChanging(value);
					this.SendPropertyChanging();
					this._TenTK = value;
					this.SendPropertyChanged("TenTK");
					this.OnTenTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoai", DbType="VarChar(20)")]
		public string DienThoai
		{
			get
			{
				return this._DienThoai;
			}
			set
			{
				if ((this._DienThoai != value))
				{
					this.OnDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._DienThoai = value;
					this.SendPropertyChanged("DienThoai");
					this.OnDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DonDatHangDoChoi_ChiTietDonDatHangDC", Storage="_ChiTietDonDatHangDCs", ThisKey="MaDonHangDC", OtherKey="MaDonHangDC")]
		public EntitySet<ChiTietDonDatHangDC> ChiTietDonDatHangDCs
		{
			get
			{
				return this._ChiTietDonDatHangDCs;
			}
			set
			{
				this._ChiTietDonDatHangDCs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_DonDatHangDoChoi", Storage="_KhachHang", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.DonDatHangDoChois.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.DonDatHangDoChois.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(Nullable<int>);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietDonDatHangDCs(ChiTietDonDatHangDC entity)
		{
			this.SendPropertyChanging();
			entity.DonDatHangDoChoi = this;
		}
		
		private void detach_ChiTietDonDatHangDCs(ChiTietDonDatHangDC entity)
		{
			this.SendPropertyChanging();
			entity.DonDatHangDoChoi = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachHang")]
	public partial class KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaKH;
		
		private string _HoTen;
		
		private string _TaiKhoan;
		
		private string _MatKhau;
		
		private string _email;
		
		private string _DienThoai;
		
		private string _DiaChi;
		
		private EntitySet<ChiTietDonDatHangDC> _ChiTietDonDatHangDCs;
		
		private EntitySet<DonDatHang> _DonDatHangs;
		
		private EntitySet<DonDatHangDoChoi> _DonDatHangDoChois;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKHChanging(int value);
    partial void OnMaKHChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnTaiKhoanChanging(string value);
    partial void OnTaiKhoanChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnDienThoaiChanging(string value);
    partial void OnDienThoaiChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    #endregion
		
		public KhachHang()
		{
			this._ChiTietDonDatHangDCs = new EntitySet<ChiTietDonDatHangDC>(new Action<ChiTietDonDatHangDC>(this.attach_ChiTietDonDatHangDCs), new Action<ChiTietDonDatHangDC>(this.detach_ChiTietDonDatHangDCs));
			this._DonDatHangs = new EntitySet<DonDatHang>(new Action<DonDatHang>(this.attach_DonDatHangs), new Action<DonDatHang>(this.detach_DonDatHangs));
			this._DonDatHangDoChois = new EntitySet<DonDatHangDoChoi>(new Action<DonDatHangDoChoi>(this.attach_DonDatHangDoChois), new Action<DonDatHangDoChoi>(this.detach_DonDatHangDoChois));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaiKhoan", DbType="VarChar(15)")]
		public string TaiKhoan
		{
			get
			{
				return this._TaiKhoan;
			}
			set
			{
				if ((this._TaiKhoan != value))
				{
					this.OnTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._TaiKhoan = value;
					this.SendPropertyChanged("TaiKhoan");
					this.OnTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoai", DbType="VarChar(20)")]
		public string DienThoai
		{
			get
			{
				return this._DienThoai;
			}
			set
			{
				if ((this._DienThoai != value))
				{
					this.OnDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._DienThoai = value;
					this.SendPropertyChanged("DienThoai");
					this.OnDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_ChiTietDonDatHangDC", Storage="_ChiTietDonDatHangDCs", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<ChiTietDonDatHangDC> ChiTietDonDatHangDCs
		{
			get
			{
				return this._ChiTietDonDatHangDCs;
			}
			set
			{
				this._ChiTietDonDatHangDCs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_DonDatHang", Storage="_DonDatHangs", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<DonDatHang> DonDatHangs
		{
			get
			{
				return this._DonDatHangs;
			}
			set
			{
				this._DonDatHangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_DonDatHangDoChoi", Storage="_DonDatHangDoChois", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<DonDatHangDoChoi> DonDatHangDoChois
		{
			get
			{
				return this._DonDatHangDoChois;
			}
			set
			{
				this._DonDatHangDoChois.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietDonDatHangDCs(ChiTietDonDatHangDC entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_ChiTietDonDatHangDCs(ChiTietDonDatHangDC entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
		
		private void attach_DonDatHangs(DonDatHang entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_DonDatHangs(DonDatHang entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
		
		private void attach_DonDatHangDoChois(DonDatHangDoChoi entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_DonDatHangDoChois(DonDatHangDoChoi entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiDoChoiXe")]
	public partial class LoaiDoChoiXe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaLoaiDC;
		
		private string _TenLoaiDC;
		
		private EntitySet<DoChoiXe> _DoChoiXes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiDCChanging(int value);
    partial void OnMaLoaiDCChanged();
    partial void OnTenLoaiDCChanging(string value);
    partial void OnTenLoaiDCChanged();
    #endregion
		
		public LoaiDoChoiXe()
		{
			this._DoChoiXes = new EntitySet<DoChoiXe>(new Action<DoChoiXe>(this.attach_DoChoiXes), new Action<DoChoiXe>(this.detach_DoChoiXes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiDC", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaLoaiDC
		{
			get
			{
				return this._MaLoaiDC;
			}
			set
			{
				if ((this._MaLoaiDC != value))
				{
					this.OnMaLoaiDCChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiDC = value;
					this.SendPropertyChanged("MaLoaiDC");
					this.OnMaLoaiDCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoaiDC", DbType="NVarChar(50)")]
		public string TenLoaiDC
		{
			get
			{
				return this._TenLoaiDC;
			}
			set
			{
				if ((this._TenLoaiDC != value))
				{
					this.OnTenLoaiDCChanging(value);
					this.SendPropertyChanging();
					this._TenLoaiDC = value;
					this.SendPropertyChanged("TenLoaiDC");
					this.OnTenLoaiDCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiDoChoiXe_DoChoiXe", Storage="_DoChoiXes", ThisKey="MaLoaiDC", OtherKey="MaLoaiDC")]
		public EntitySet<DoChoiXe> DoChoiXes
		{
			get
			{
				return this._DoChoiXes;
			}
			set
			{
				this._DoChoiXes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DoChoiXes(DoChoiXe entity)
		{
			this.SendPropertyChanging();
			entity.LoaiDoChoiXe = this;
		}
		
		private void detach_DoChoiXes(DoChoiXe entity)
		{
			this.SendPropertyChanging();
			entity.LoaiDoChoiXe = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhuKien")]
	public partial class PhuKien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaPhuKien;
		
		private string _Phukien1;
		
		private EntitySet<ChiTietPhuKien> _ChiTietPhuKiens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhuKienChanging(int value);
    partial void OnMaPhuKienChanged();
    partial void OnPhukien1Changing(string value);
    partial void OnPhukien1Changed();
    #endregion
		
		public PhuKien()
		{
			this._ChiTietPhuKiens = new EntitySet<ChiTietPhuKien>(new Action<ChiTietPhuKien>(this.attach_ChiTietPhuKiens), new Action<ChiTietPhuKien>(this.detach_ChiTietPhuKiens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhuKien", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaPhuKien
		{
			get
			{
				return this._MaPhuKien;
			}
			set
			{
				if ((this._MaPhuKien != value))
				{
					this.OnMaPhuKienChanging(value);
					this.SendPropertyChanging();
					this._MaPhuKien = value;
					this.SendPropertyChanged("MaPhuKien");
					this.OnMaPhuKienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Phukien", Storage="_Phukien1", DbType="NVarChar(50)")]
		public string Phukien1
		{
			get
			{
				return this._Phukien1;
			}
			set
			{
				if ((this._Phukien1 != value))
				{
					this.OnPhukien1Changing(value);
					this.SendPropertyChanging();
					this._Phukien1 = value;
					this.SendPropertyChanged("Phukien1");
					this.OnPhukien1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhuKien_ChiTietPhuKien", Storage="_ChiTietPhuKiens", ThisKey="MaPhuKien", OtherKey="MaPhuKien")]
		public EntitySet<ChiTietPhuKien> ChiTietPhuKiens
		{
			get
			{
				return this._ChiTietPhuKiens;
			}
			set
			{
				this._ChiTietPhuKiens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietPhuKiens(ChiTietPhuKien entity)
		{
			this.SendPropertyChanging();
			entity.PhuKien = this;
		}
		
		private void detach_ChiTietPhuKiens(ChiTietPhuKien entity)
		{
			this.SendPropertyChanging();
			entity.PhuKien = null;
		}
	}
}
#pragma warning restore 1591
